# Aula de álgebra Linear - vetores

## Vamos começar definindo uma variável

### No python é possível fazer cálculos de maneira direta

In [ ]:
5*3

### Normalmente é melhor atribuir cada valor a uma variável, e depois pedir o cálculo

In [7]:
x = 5
y = 3

In [ ]:
x*y

### Mas como fazer para atribuir valores a vetores no python?

In [2]:
a = [1,2]

In [10]:
b = [0,3]

In [ ]:
a[0]

In [15]:
a[1]

2

In [ ]:
a+b

## Produto Escalar

### O python tem uma biblioteca, a numpy, que tem uma função que resolve o produto escalar

In [36]:
import numpy as np

vetor1 = np.array([1, 2])
vetor2 = np.array([0,3])

produto_escalar = np.inner(vetor1, vetor2)
print(produto_escalar)

6


### E também uma função para calcular o módulo de um vetor

In [32]:
modulo = np.linalg.norm(vetor1)
print(f"O módulo do vetor é: {modulo:.2f}")

O módulo do vetor é: 2.24


### Como multiplicar um escalar por um vetor?

In [31]:
k = 2
vetor_a = k*vetor1
vetor_a

array([2, 4])

### Para calcular o ângulo entre dois vetores, precisamos v

In [37]:
import numpy as np

def calcular_angulo_numpy(vetor1, vetor2):
    cos_theta = np.dot(vetor1, vetor2) / (np.linalg.norm(vetor1) * np.linalg.norm(vetor2))
    angulo_radianos = np.arccos(cos_theta)
    angulo_graus = np.degrees(angulo_radianos)
    return angulo_graus

# Exemplo de uso
vetor_a = np.array([1, 2, 3])
vetor_b = np.array([4, 5, 6])
angulo = calcular_angulo_numpy(vetor_a, vetor_b)
print(f"Ângulo entre os vetores: {angulo:.2f} graus")

Ângulo entre os vetores: 12.93 graus


# Produto Vetorial

In [23]:
import numpy as np

vetor1 = np.array([1, 2, 3])
vetor2 = np.array([4, 5, 6])

vetor_3 = np.cross(vetor1, vetor2)
print(produto_vetorial)

[-3  6 -3]


In [27]:
vetor4 = np.cross(vetor_3,vetor1)
vetor4

array([  6,  -3, -12])